#!/usr/bin/env bash

## Catppuccin theme
COLOR_BAR_BACKGROUND="#332E41"
COLOR_BAR_FOREGROUND="#B7E5E6"
COLOR_BACKGROUND="#332E41"
COLOR_FOREGROUND="#DFDEF1"
COLOR_FOREGROUND_DARK="#988BA2"
COLOR_PRIMARY="#C6AAE8"
COLOR_SECONDARY="#DFDEF1"
COLOR_ALTERNATE="#C6AAE8"
COLOR_INACTIVE="#6E6C7E"
COLOR_BORDER_ACTIVE="#C6AAE8"
COLOR_BORDER_INACTIVE="#1E1E28"
COLOR_BORDER_FLOATING="#F2CDCD"
COLOR_APPLET_BACKGROUND="#332E41"
COLOR_APPLET_BACKGROUND_LIGHT="#575268"